# Generated by Django 2.0.5 on 2018-05-31 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum_events', '0002_auto_20180531_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredevent',
            name='event_abi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitoredevent',
            name='topic',
            field=models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)]),
        ),
    ]
