# Generated by Django 2.0.5 on 2018-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum_events', '0004_failedeventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='block_number',
            field=models.IntegerField(default=0, help_text='Last block processed'),
        ),
    ]
